// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gatherRoundItasca.Server.Data;

#nullable disable

namespace gatherRoundItasca.Server.Migrations
{
    [DbContext(typeof(ExploreItascaContext))]
    partial class ExploreItascaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gatherRoundItasca.Server.Models.GroupModel", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupLeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupMembers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupPlace")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupPlace");

                    b.ToTable("GroupModel");
                });

            modelBuilder.Entity("gatherRoundItasca.Server.Models.LeaderboardModel", b =>
                {
                    b.Property<int?>("Place")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Place"));

                    b.Property<string>("PlayerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("RankingPlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Place");

                    b.HasIndex("RankingPlayerId");

                    b.ToTable("LeaderboardModel");
                });

            modelBuilder.Entity("gatherRoundItasca.Server.Models.LocationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Riddle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("gatherRoundItasca.Server.Models.PlayerDataModel", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteAnimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("gatherRoundItasca.Server.Models.UpdateModel", b =>
                {
                    b.Property<int>("UpdateNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateNumber"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaderboardUpdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationUpdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UpdateNumber");

                    b.ToTable("Updates");
                });

            modelBuilder.Entity("gatherRoundItasca.Server.Models.GroupModel", b =>
                {
                    b.HasOne("gatherRoundItasca.Server.Models.LeaderboardModel", "Group")
                        .WithMany("Groups")
                        .HasForeignKey("GroupPlace");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("gatherRoundItasca.Server.Models.LeaderboardModel", b =>
                {
                    b.HasOne("gatherRoundItasca.Server.Models.PlayerDataModel", "Ranking")
                        .WithMany("Place")
                        .HasForeignKey("RankingPlayerId");

                    b.Navigation("Ranking");
                });

            modelBuilder.Entity("gatherRoundItasca.Server.Models.LeaderboardModel", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("gatherRoundItasca.Server.Models.PlayerDataModel", b =>
                {
                    b.Navigation("Place");
                });
#pragma warning restore 612, 618
        }
    }
}
